# 2d23c4de000b42bf92d9ad8597f7fdc0
version: '3.9'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    command: ["--httpPort=8090"]
    volumes:
      - jenkins-data:/var/jenkins_home
    ports:
      - "8090:8090"
      - "50000:50000"

volumes:
  jenkins-data:
    name: jenkins-data
